name: CI - Build & Test with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # pull your repository code into the GitHub-hosted runner
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
c
      # Bring up db + run tests service in the same Compose graph.
      - name: Build & run tests with Docker Compose
        run: |
          docker compose \
            -f docker-compose.yml \
            -f docker-compose.ci.yml \
            up --build --exit-code-from tests --abort-on-container-exit tests

      # (Optional) Show logs if something fails
      - name: Dump container logs on failure
        if: failure()
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml logs db || true

      # Clean up
      - name: Tear down
        if: always()
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml down -v
