name: CI - Build & Test with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # pull your repository code into the GitHub-hosted runner
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # Bring up db + run tests service in the same Compose graph.
      - name: Build & run tests with Docker Compose
        run: |
          docker compose \
            -f docker-compose.yml \
            -f docker-compose.ci.yml \
            up --build --exit-code-from tests --abort-on-container-exit tests

      # (Optional) Show logs if something fails
      - name: Dump container logs on failure
        if: failure()
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml logs db || true

      # Clean up
      - name: Tear down
        if: always()
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml down -v

  deploy:
    # Only deploy on pushes to main, not on PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys \
            -d '{}'